layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

  social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: ganesh.karkhani
  hackerrank: gani_24
  instagram: ganesh_karkhani
  # keybase: your_username
  #linkedin: username
  # mastodon: your_username
  #medium: username
  #stackoverflow: 
  telegram: Gun_2415
  #twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username


topics:
  - name: Python
    web_url: https://github.com/search?q=python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Youtube
    web_url: https://www.youtube.com/channel/UCxZhpXve-BmOuzvXw4_qEew
    image_url: https://w7.pngwing.com/pngs/936/468/png-transparent-youtube-logo-youtube-logo-computer-icons-subscribe-angle-rectangle-airplane.png

  - name: Html
    web_url: https://github.com/search?q=HTML&type=Repositories
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/html/html.png
